### PR TITLE
CSS: Migrate main elements to Tailwind

### PR DESCRIPTION
**Pull request by wei2912**
This PR contains changes to migrate the main elements of pages to Tailwind.

### CODE REVIEW

**Comment by wei2912** [comment]
@bnjmnt4n Do you have any idea how to properly manage the font sizes in `assets/css/components/global.css`? For some reason `html` has `font-size: 62.5%` and `body` has `font-size: 1.5rem`...

Also, is there any good alternative to `vw`, `vh`, etc? I had trouble migrating some of the stuff in `assets/css/screen.css` because Tailwind doesn't have rules for stuff like `4vw`.

**Review by bnjmnt4n — APPROVED** [review]
I think this looks like a great start.

> @bnjmnt4n Do you have any idea how to properly manage the font sizes in assets/css/components/global.css? For some reason html has font-size: 62.5% and body has font-size: 1.5rem...

As mentioned in chat privately, that was a relic typically used in older days to allow for easier multiplication of font sizes (62.5% * 16px = 10px, so 1rem = 10px). I think an easy escape route is to just delete the whole `global.css` file, defaulting to browser defaults, and make use of Tailwind's font-size classes when we need to (https://tailwindcss.com/docs/font-size).

I think the uses of the `vh`, `vw` units are pretty minor, and switching to explicit defined units via Tailwind classes shouldn't be a problem.

**Comment by wei2912** [comment]
Just to update, the above changes set the `font-size` of `body` back to `100%`, and amends all `rem`s to reflect this value. In addition, it replaces some of the files with Tailwind styles.

These changes are likely to break the typography of the website, but I plan to use Tailwind's typography plugin (https://tailwindcss-typography.netlify.app/) to fix that in the future.

**Comment by wei2912** [comment]
I'll be merging this in first with all commits rebased, so that it'll be easier to revert any of them. This is likely to break the styling of the website slightly, but I guess it's better that we break the styling now so that it can be fixed later.

**Pull request merged**
